// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Playlist struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Queue struct {
	IDPlaylist int32  `json:"id_playlist"`
	TitleSong  string `json:"title_song"`
	Position   int32  `json:"position"`
}

type Song struct {
	Title    string `json:"title"`
	Genre    string `json:"genre"`
	Artist   string `json:"artist"`
	Duration int32  `json:"duration"`
}
