// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	ClearQueue(ctx context.Context, idPlaylist int32) error
	CreatePlaylist(ctx context.Context, name string) (Playlist, error)
	CreateQueue(ctx context.Context, arg CreateQueueParams) (Queue, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeletePlaylist(ctx context.Context, id int32) error
	DeleteQueue(ctx context.Context, arg DeleteQueueParams) error
	DeleteSong(ctx context.Context, title string) error
	GetPlaylist(ctx context.Context, id int32) (Playlist, error)
	GetPlaylists(ctx context.Context) ([]Playlist, error)
	GetQueues(ctx context.Context, idPlaylist int32) ([]GetQueuesRow, error)
	GetSongs(ctx context.Context) ([]Song, error)
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdateQueue(ctx context.Context, arg UpdateQueueParams) (Queue, error)
}

var _ Querier = (*Queries)(nil)
